- name: test copy
  hosts: all
  become: true

  tasks:
  - name: Synchronization of src on the control machine to dest on the remote hosts
    synchronize:
      src: myfile.txt
      dest: /tmp/myfile.txt
      group: yes
      owner: yes
      rsync_opts:
#      - "--chown=testuser:testuser"
       - "--usermap=awx:testuser"
       - "--groupmap=awx:testuser"
