- name: Run some tasks on managed node
  hosts: all

    machine:
    username: '{{ ansible_user }}'
    pvkey: '{{ ansible_ssh_private_key_file }}'

  tasks:
  - setup:

  - shell: "whoami"

  - shell: "hostname"

  - debug:
    var: pvkey
