- name: launch a workflow
  hosts: localhost
  connection: local
  gather_facts: false

  collections: 
  - awx.awx

  tasks:
  - name: launch tower workflow
    tower_workflow_launch:
      tower_username: "{{ toweruser }}"
      tower_password: "{{ towerpass }}"
      tower_host: "{{ towerurl }}"
      validate_certs: false
      workflow_template: "{{ workflowvar }}"
      limit: "{{ limitvar }}"
      wait: false
