# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.disksize.size = '50GB'


  config.vm.define "tower1" do |tower1|
    tower1.vm.hostname = "tower1"
    tower1.vm.box = "centos/7"
    tower1.vm.network "private_network", ip: "172.16.33.20"
    for p in [:virtualbox, :libvirt] do
      tower1.vm.provider p do |provider|
        provider.memory = 4068
        provider.cpus = 2
      end
    end
  end

  config.vm.define "tower2" do |tower2|
    tower2.vm.hostname = "tower2"
    tower2.vm.box = "centos/7"
    tower2.vm.network "private_network", ip: "172.16.33.21"
    for p in [:virtualbox, :libvirt] do
      tower2.vm.provider p do |provider|
        provider.memory = 4068
        provider.cpus = 2
      end
    end
  end

  config.vm.define "tower3" do |tower3|
    tower3.vm.hostname = "tower3"
    tower3.vm.box = "centos/7"
    tower3.vm.network "private_network", ip: "172.16.33.23"
    for p in [:virtualbox, :libvirt] do
      tower3.vm.provider p do |provider|
        provider.memory = 4068
        provider.cpus = 2
      end
    end
  end

  config.vm.define "towerdb" do |towerdb|
    towerdb.vm.hostname = "towerdb"
    towerdb.vm.box = "centos/7"
    towerdb.vm.network "private_network", ip: "172.16.33.22"
    for p in [:virtualbox, :libvirt] do
      towerdb.vm.provider p do |provider|
        provider.memory = 4068
        provider.cpus = 3
      end
    end
  end

  config.vm.define "isonode" do |isonode|
    isonode.vm.hostname = "isonode"
    isonode.vm.box = "centos/7"
    isonode.vm.network "private_network", ip: "172.16.33.22"
    for p in [:virtualbox, :libvirt] do
      isonode.vm.provider p do |provider|
        provider.memory = 4068
        provider.cpus = 3
      end
    end
  end

end
